integration_name: com.newrelic.zookeeper

instances:
  - name: {{ ansible_fqdn }}
    command: metrics
    arguments:
      host: zookeeper-node
      port: 2181
      cmd: nc
    labels:
      role: zookeeper
      env: {{ zookeeperEnvironment }}